<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Module5\PositionTitle;
use App\Models\Module5\FieldOffice;
use App\Models\Module5\PesoCarouselSlide;

class PesoDirectorySeeder extends Seeder
{
    public function run(): void
    {
        
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        FieldOffice::truncate();
        PositionTitle::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $titles = [];
        $titles['MANAGER']      = PositionTitle::create(['name' => 'MANAGER'])->id;
        $titles['PESO MANAGER'] = PositionTitle::create(['name' => 'PESO MANAGER'])->id;
        $titles['DISTRICT HEAD']= PositionTitle::create(['name' => 'DISTRICT HEAD'])->id;
        $titles['JPO MANAGER']  = PositionTitle::create(['name' => 'JPO MANAGER'])->id; 
        $PESO = 1;
        $JPO  = 2;

        $offices = [
            // ─── DAVAO ORIENTAL ───────────────────────────────────────────────
            [
                'province'        => 'DAVAO ORIENTAL',
                'name'            => 'PESO DAVAO ORIENTAL',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'JAY O. DAYANGHIRANG',
                'email'           => 'davorpeso@gmail.com',
                'address'         => 'Provincial Capitol, Mati Ciy, Davao Oriental',
                'sort_order'      => 1,
            ],
            [
                'province'        => 'DAVAO ORIENTAL',
                'name'            => 'PESO MATI CITY',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'PAULINE ELSA F. OLITA',
                'email'           => 'olitapaulineelsa@gmail.com',
                'address'         => 'Mati Ciy, Davao Oriental',
                'sort_order'      => 2,
            ],
            [
                'province'        => 'DAVAO ORIENTAL',
                'name'            => 'PESO BANAYBANAY',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'ANALIE E. NOGALIZA',
                'email'           => 'marialindadalapalan@gmail.com',
                'address'         => 'Municipality Hall, Poblacion, Banaybanay, Davao Oriental',
                'sort_order'      => 3,
            ],
            [
                'province'        => 'DAVAO ORIENTAL',
                'name'            => 'PESO LUPON',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'ANNA MARIZ R. FELICIADOS',
                'email'           => 'mariz.feliciados@gmail.com',
                'address'         => 'New Municipal Hall, National Highway, Bagumbayan, Lupon, Davao Oriental',
                'sort_order'      => 4,
            ],
            [
                'province'        => 'DAVAO ORIENTAL',
                'name'            => 'PESO SAN ISIDRO',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'EDGAR S. LINGATONG',
                'email'           => 'pesosanisidro@gmail.com',
                'address'         => 'San Isidro, Davao Oriental',
                'sort_order'      => 5,
            ],
            [
                'province'        => 'DAVAO ORIENTAL',
                'name'            => 'PESO GOVERNOR GENEROSO',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'JUVY P. MARIMON',
                'email'           => 'juvypandac1974@gmail.com',
                'address'         => 'Governor Generoso, Davao Oriental',
                'sort_order'      => 6,
            ],
            [
                'province'        => 'DAVAO ORIENTAL',
                'name'            => 'PESO MANAY',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'ANNIELLOU JOY D. BITAC',
                'email'           => 'ajdbitac@yahoo.com',
                'address'         => 'LGU Main Building, Manay, Davao Oriental',
                'sort_order'      => 7,
            ],
            [
                'province'        => 'DAVAO ORIENTAL',
                'name'            => 'PESO CARAGA',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'JOHN KENNETH G. MENDOZA',
                'email'           => 'verdantlatency@gmail.com',
                'address'         => 'DonLeon St., Poblacion, Caraga, Davao Oriental',
                'sort_order'      => 8,
            ],
            [
                'province'        => 'DAVAO ORIENTAL',
                'name'            => 'PESO BAGANGA',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'VACANT',
                'email'           => 'bagangapesooffice@gmail.com',
                'address'         => 'Baganga, Davao Oriental',
                'sort_order'      => 9,
            ],
            [
                'province'        => 'DAVAO ORIENTAL',
                'name'            => 'PESO CATEEL',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'Bryan Ephraem E. Miguel',
                'email'           => 'pesocateel@gmail.com',
                'address'         => '2F Cateel Public Transport Terminal, Poblacion. Cateel, Davao Oriental',
                'sort_order'      => 10,
            ],
            [
                'province'        => 'DAVAO ORIENTAL',
                'name'            => 'PESO BOSTON',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'DANILO G. BRILLANTES',
                'email'           => 'danilobrillantes@gmail.com',
                'address'         => 'Municipal Hall, St., Poblacion, Boston, Davao Oriental',
                'sort_order'      => 11,
            ],
            [
                'province'        => 'DAVAO ORIENTAL',
                'name'            => 'PESO TARRAGONA',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'NENITA T. CARASCA',
                'email'           => 'pesotarragona@gmail.com',
                'address'         => 'LGU Tarragona, Davao Oriental',
                'sort_order'      => 12,
            ],
            [
                'province'        => 'DAVAO ORIENTAL',
                'name'            => 'JPO DAVAO ORIENTAL STATE UNIVERSITY',
                'office_type_id'  => $JPO,
                'position_title'  => 'JPO MANAGER',
                'persons_name'    => 'TRISHEA AMOR C. JACOBE',
                'email'           => 'pesodoscst@gmail.com',
                'address'         => 'City of Mati, Davao Oriental',
                'sort_order'      => 13,
            ],
            [
                'province'        => 'DAVAO ORIENTAL',
                'name'            => 'JPO DON BOSCO TRAINING CENTER',
                'office_type_id'  => $JPO,
                'position_title'  => 'JPO MANAGER',
                'persons_name'    => 'NINO A. JUAREZ',
                'email'           => 'donboscomati12.peso@gmail.com',
                'address'         => 'City of Mati, Davao Oriental',
                'sort_order'      => 14,
            ],
            [
                'province'        => 'DAVAO ORIENTAL',
                'name'            => "JPO CHRISTIAN ACADEMY OF DAVAO ORIENTAL, INC.",
                'office_type_id'  => $JPO,
                'position_title'  => 'JPO MANAGER',
                'persons_name'    => 'CHRYSTIE PAZ A. JANDAYAN',
                'email'           => 'pyaxz@yahoo.com',
                'address'         => 'City of Mati, Davao Oriental',
                'sort_order'      => 15,
            ],
            [
                'province'        => 'DAVAO ORIENTAL',
                'name'            => "JPO SAINT MARY'S COLLEGE OF BAGANGA",
                'office_type_id'  => $JPO,
                'position_title'  => 'JPO MANAGER',
                'persons_name'    => 'MARIZ M. LABOS',
                'email'           => 'smcbdo.guidance@gmail.com',
                'address'         => 'Baganga, Davao Oriental',
                'sort_order'      => 16,
            ],
            [
                'province'        => 'DAVAO ORIENTAL',
                'name'            => 'JPO MATI POLYTECHNIC COLLEGE',
                'office_type_id'  => $JPO,
                'position_title'  => 'JPO MANAGER',
                'persons_name'    => 'DR. Janice Bernadeth G. Agbong',
                'email'           => 'polytechnicmati@yahoo.com',
                'address'         => 'Don Mariano Marcos Ave., Brgy. Sainz, City of Mati, Davao Oriental',
                'sort_order'      => 17,
            ],

            // ─── DAVAO DE ORO ─────────────────────────────────────────────────
            [
                'province'        => 'DAVAO DE ORO',
                'name'            => 'PESO DAVAO DE ORO',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'MILES A. ATUGAN',
                'email'           => 'pesodavaodeoro@gmail.com',
                'address'         => 'Cabidianan, Nabunturan, Davao de Oro',
                'sort_order'      => 18,
            ],
            [
                'province'        => 'DAVAO DE ORO',
                'name'            => 'PESO COMPOSTELA',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'LORETO JR B DOYDOY',
                'email'           => 'pesocteccompostela@gmail.com',
                'address'         => 'Poblacion, Compostela Davao de oro',
                'sort_order'      => 19,
            ],
            [
                'province'        => 'DAVAO DE ORO',
                'name'            => 'PESO LAAK',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'PHILIP D. CHIU',
                'email'           => 'philipdchiu0667@gmail.com / pesolaak2014@gmail.com',
                'address'         => 'Poblacion Laak, Davao de Oro',
                'sort_order'      => 20,
            ],
            [
                'province'        => 'DAVAO DE ORO',
                'name'            => 'PESO MABINI',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'EDWIN REY A. CARMELOTES',
                'email'           => 'mabiniddo.peso8807@gmail.com',
                'address'         => 'Prk. Makugihon, Cuambog, Mabini, Davao de Oro',
                'sort_order'      => 21,
            ],
            [
                'province'        => 'DAVAO DE ORO',
                'name'            => 'PESO MACO',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'CONCEPCION C. CONCHA',
                'email'           => 'hrmo_peso_maco@yahoo.com',
                'address'         => 'Binuangan, Maco, Davao de Oro',
                'sort_order'      => 22,
            ],
            [
                'province'        => 'DAVAO DE ORO',
                'name'            => 'PESO MARAGUSAN',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'EVELIZA W. PANTINOPLE',
                'email'           => 'peesomaragusan2025@gmail.com',
                'address'         => 'Brgy. Poblacion, Maragusan',
                'sort_order'      => 23,
            ],
            [
                'province'        => 'DAVAO DE ORO',
                'name'            => 'PESO MAWAB',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'ANNA AYESA B. ARAMBALA',
                'email'           => 'peso_mawab@yahoo.com',
                'address'         => 'Brgy. Poblacion, Mawab',
                'sort_order'      => 24,
            ],
            [
                'province'        => 'DAVAO DE ORO',
                'name'            => 'PESO MONKAYO',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'AISA P. TIA',
                'email'           => 'pesomonkayo@gmail.com',
                'address'         => 'Poblacion Monkayo, Davao de Oro',
                'sort_order'      => 25,
            ],
            [
                'province'        => 'DAVAO DE ORO',
                'name'            => 'PESO MONTEVISTA',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'WALTER C. DALAGAN',
                'email'           => 'peso.montevista123@gmail.com',
                'address'         => 'Poblacion Montevista, Davao de Oro',
                'sort_order'      => 26,
            ],
            [
                'province'        => 'DAVAO DE ORO',
                'name'            => 'PESO NABUNTURAN',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'MARIETA CALAGO',
                'email'           => 'mayetcalago@gmail.com',
                'address'         => 'Brgy. Magsaysay, Nabunturan, Davao de Oro',
                'sort_order'      => 27,
            ],
            [
                'province'        => 'DAVAO DE ORO',
                'name'            => 'PESO NEW BATAAN',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'ESTRELLA L. POTENCIANO',
                'email'           => 'pesonewbataan@gmail.com',
                'address'         => 'Espaola Street, Cabinuangan, New Bataan, Davao de Oro',
                'sort_order'      => 28,
            ],
            [
                'province'        => 'DAVAO DE ORO',
                'name'            => 'PESO PANTUKAN',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'NITCHELL A. ACEDILLO, DBA',
                'email'           => 'pesopantukan2022@gmail.com',
                'address'         => 'TOWSITE, KINGKING, PANTUKAN, DAVAO DE ORO',
                'sort_order'      => 29,
            ],
            [
                'province'        => 'DAVAO DE ORO',
                'name'            => 'JPO ASSUMPTION COLLEGE OF NABUNTURAN',
                'office_type_id'  => $JPO,
                'position_title'  => 'JPO MANAGER',
                'persons_name'    => 'GLYDYL DALIRE',
                'email'           => 'glendabejona1@gmail.com',
                'address'         => 'Panabo City',
                'sort_order'      => 30,
            ],
            [
                'province'        => 'DAVAO DE ORO',
                'name'            => 'JPO DAVAO DE ORO STATE COLLEGE',
                'office_type_id'  => $JPO,
                'position_title'  => 'JPO MANAGER',
                'persons_name'    => 'JUDALYN J. FORRO, MPsych',
                'email'           => 'judalyn.forro@ddosc.edu.ph',
                'address'         => 'Compostela, Davao de Oro',
                'sort_order'      => 31,
            ],
            [
                'province'        => 'DAVAO DE ORO',
                'name'            => 'JPO Monkayo College of Arts, Sciences and Technology',
                'office_type_id'  => $JPO,
                'position_title'  => 'JPO MANAGER',
                'persons_name'    => 'MIKE BACARO',
                'email'           => 'rhyrhy0521@gmail.com',
                'address'         => 'Monkayo, Davao de Oro',
                'sort_order'      => 32,
            ],
            [
                'province'        => 'DAVAO DE ORO',
                'name'            => 'JPO Maco de Oro College',
                'office_type_id'  => $JPO,
                'position_title'  => 'JPO MANAGER',
                'persons_name'    => 'DR. ANTHONY POL FULACHE',
                'email'           => 'macodeorocollege2019@gmail.com',
                'address'         => 'Prk. 3 Hijo, Maco, Davao de Oro',
                'sort_order'      => 33,
            ],

            // ─── DAVAO DEL SUR ────────────────────────────────────────────────
            [
                'province'        => 'DAVAO DEL SUR',
                'name'            => 'PESO DAVAO DEL SUR',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'ROLLY M. IMPAS, LPT, MBA, J.D',
                'email'           => 'davaodelsurpeso@gmail.com',
                'address'         => 'PROVINCIAL CAPITOL, MATTI, DIGOS CITY, DAVAO DEL SUR',
                'sort_order'      => 34,
            ],
            [
                'province'        => 'DAVAO DEL SUR',
                'name'            => 'PESO DIGOS CITY',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'SHANY LOU R. SOLATORIO, MPA',
                'email'           => 'digoscitypeso@gmail.com; shanylou88@gmail.com',
                'address'         => 'JOSE ABAD SANTOS ST., DIGOS CITY, DAVAO DEL SUR',
                'sort_order'      => 35,
            ],
            [
                'province'        => 'DAVAO DEL SUR',
                'name'            => 'PESO BANSALAN',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'CORY B. CHATTO, REA',
                'email'           => 'corybaloriocha2@gmail.com',
                'address'         => 'BANSALAN, DAVAO DEL SUR',
                'sort_order'      => 36,
            ],
            [
                'province'        => 'DAVAO DEL SUR',
                'name'            => 'PESO HAGONOY',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'AGNES C. LABADAN',
                'email'           => 'neslabadan70@gmail.com',
                'address'         => 'HAGONOY, DAVAO DEL SUR',
                'sort_order'      => 37,
            ],
            [
                'province'        => 'DAVAO DEL SUR',
                'name'            => 'PESO KIBLAWAN',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'CONTEZA MAY F. SENOY',
                'email'           => 'tezafiel02@gmail.com',
                'address'         => 'KIBLAWAN, DAVAO DEL SUR',
                'sort_order'      => 38,
            ],
            [
                'province'        => 'DAVAO DEL SUR',
                'name'            => 'PESO MAGSAYSAY',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'LEONILE P. ESCARPE',
                'email'           => 'magsaysaypeso@gmail.com',
                'address'         => 'MAGSAYSAY, DAVAO DEL SUR',
                'sort_order'      => 39,
            ],
            [
                'province'        => 'DAVAO DEL SUR',
                'name'            => 'PESO MALALAG',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'JUANZO G. CALUMPONG',
                'email'           => 'jcalumpong557@gmail.com elsieselgas76@gmail.com',
                'address'         => 'MALALAG, DAVAO DEL SUR',
                'sort_order'      => 40,
            ],
            [
                'province'        => 'DAVAO DEL SUR',
                'name'            => 'PESO MATANAO',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'MICHAEL MARK B. DELA VICTORIA',
                'email'           => 'mdelavictoria24@gmail.com',
                'address'         => 'MATANAO, DAVAO DEL SUR',
                'sort_order'      => 41,
            ],
            [
                'province'        => 'DAVAO DEL SUR',
                'name'            => 'PESO PADADA',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'MARK HILL M. DELOS REYES',
                'email'           => 'wilmeeghot901@gmail.com',
                'address'         => 'RIZAL ST. NCO DISTRICT, PADADA, DAVAO DEL SUR',
                'sort_order'      => 42,
            ],
            [
                'province'        => 'DAVAO DEL SUR',
                'name'            => 'PESO STA. CRUZ',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'MA. CHERYL D. SERENATAS',
                'email'           => 'peso_stacruz@yahoo.com pesosantacruz05@gmail.com mcserenatas0911@gmail.com',
                'address'         => 'STA. CRUZ, DAVAO DEL SUR',
                'sort_order'      => 43,
            ],
            [
                'province'        => 'DAVAO DEL SUR',
                'name'            => 'PESO SULOP',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'MARY ANN FERENAL-CODILLA',
                'email'           => 'pesosulop07@gmail.com decembernovember0311@gmail.com',
                'address'         => 'SULOP, DAVAO DEL SUR',
                'sort_order'      => 44,
            ],
            [
                'province'        => 'DAVAO DEL SUR',
                'name'            => 'JPO COR JESU COLLEGE, INC.',
                'office_type_id'  => $JPO,
                'position_title'  => 'JPO MANAGER',
                'persons_name'    => 'JINGLE S. NAVAREZ, MAED',
                'email'           => 'jinglenavarez@g.cjc.edu.ph',
                'address'         => 'SACRED HEART AVE., DIGOS CITY, DAVAO DEL SUR',
                'sort_order'      => 45,
            ],
            [
                'province'        => 'DAVAO DEL SUR',
                'name'            => 'JPO DAVAO DEL SUR STATE COLLEGE (SPAMAST DIGOS)',
                'office_type_id'  => $JPO,
                'position_title'  => 'JPO MANAGER',
                'persons_name'    => 'PEARL LETTEE D. MAUNES, MBA',
                'email'           => 'eraaodigos@umindanao.edu.ph pearlletteemaunes@umindanao.edu.ph',
                'address'         => '3361, JOSE ABAD SANTOS ST., DIGOS CITY, DAVAO DEL SUR',
                'sort_order'      => 46,
            ],
            [
                'province'        => 'DAVAO DEL SUR',
                'name'            => 'JPO DAVAO DEL SUR STATE COLLEGE (SPAMAST DIGOS)',
                'office_type_id'  => $JPO,
                'position_title'  => 'JPO MANAGER',
                'persons_name'    => 'ARNIE B. GRAJO',
                'email'           => 'jpo@dssc.edu.ph',
                'address'         => 'MATTI, DIGOS CITY, DAVAO DEL SUR',
                'sort_order'      => 47,
            ],
            [
                'province'        => 'DAVAO DEL SUR',
                'name'            => 'JPO POLYTECHNIC COLLEGE OF DAVAO DEL SUR',
                'office_type_id'  => $JPO,
                'position_title'  => 'JPO MANAGER',
                'persons_name'    => 'DR. JESUSA E. TRINIDAD, RST, RGC',
                'email'           => 'amelie.bello@dssc.edu.ph lady-ams80@yahoo.com',
                'address'         => 'DIGOS CITY, DAVAO DEL SUR',
                'sort_order'      => 48,
            ],

            // ─── DAVAO OCCIDENTAL ─────────────────────────────────────────────
            [
                'province'        => 'DAVAO OCCIDENTAL',
                'name'            => 'PESO DAVAO OCCIDENTAL',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'Wilson G. Monesit',
                'email'           => 'pesodavaooccidentall@gmail.com',
                'address'         => 'Poblacion, Malita, Davao Occidental',
                'sort_order'      => 49,
            ],
            [
                'province'        => 'DAVAO OCCIDENTAL',
                'name'            => 'PESO DON MARCELINO',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'Jorge D. Gildore',
                'email'           => 'jorge.gildore@gmail.com',
                'address'         => 'Brgy. Lawa, Don Marcelino, Davao Occidental',
                'sort_order'      => 50,
            ],
            [
                'province'        => 'DAVAO OCCIDENTAL',
                'name'            => 'PESO JOSE ABAD SANTOS',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'Winnie P. Malanas',
                'email'           => 'winnie.malanas01@deped.gov.ph / winniemalanas43@gmail.com',
                'address'         => 'Caburan Small, Jose Abad Santos, Davao Occidental',
                'sort_order'      => 51,
            ],
            [
                'province'        => 'DAVAO OCCIDENTAL',
                'name'            => 'PESO MALITA',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'Stelito M. Jumaran',
                'email'           => 'pesomalitalgu@gmail.com',
                'address'         => 'Poblacion, Malita Davao Occidental',
                'sort_order'      => 52,
            ],
            [
                'province'        => 'DAVAO OCCIDENTAL',
                'name'            => 'PESO STA. MARIA',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'Angelo D. Carr',
                'email'           => 'pesostamaria907@gmail.com',
                'address'         => 'Poblacion, Santa Maria, Davao Occidental',
                'sort_order'      => 53,
            ],
            [
                'province'        => 'DAVAO OCCIDENTAL',
                'name'            => 'PESO SARANGANI',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'Reaggie Nolan L. Regino',
                'email'           => 'pesodavaocc@gmail.com',
                'address'         => 'Mabila, Sarangani, Davao Occidental',
                'sort_order'      => 54,
            ],
            [
                'province'        => 'DAVAO OCCIDENTAL',
                'name'            => 'JPO Southern Philippines Agri-business & Marine & Aquatic School of Technology (SPAMAST)',
                'office_type_id'  => $JPO,
                'position_title'  => 'JPO MANAGER',
                'persons_name'    => 'Deanne Abigail C. Bugawisan',
                'email'           => 'm.depalubos@spamast.edu.ph',
                'address'         => 'Malita, Davao Occidental',
                'sort_order'      => 55,
            ],

            // ─── DAVAO DEL NORTE ──────────────────────────────────────────────
            [
                'province'        => 'DAVAO DEL NORTE',
                'name'            => 'PESO DAVAO DEL NORTE',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'GLORIA EXCELSA S. PAMUGAS',
                'email'           => 'ddnpesolmi@gmail.com',
                'address'         => 'DavNor TechVoc Center, Provincial Government Center, Mankilam, Tagum City',
                'sort_order'      => 56,
            ],
            [
                'province'        => 'DAVAO DEL NORTE',
                'name'            => 'PESO TAGUM CITY',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'Mae-Ann M. Ang',
                'email'           => 'tagumpeso@gmail.com tagumpeeso@tagumcity.gov.ph',
                'address'         => 'New City Hall, Apokon, Tagum City',
                'sort_order'      => 57,
            ],
            [
                'province'        => 'DAVAO DEL NORTE',
                'name'            => 'PESO PANABO CITY',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'Cherelle B. Espinosa',
                'email'           => 'pesopanabocity@gmail.com pesopanabo@yahoo.com',
                'address'         => 'City Parks and Plaza, Brgy. New Pandan, Panabo City',
                'sort_order'      => 58,
            ],
            [
                'province'        => 'DAVAO DEL NORTE',
                'name'            => 'PESO ISLAND GARDEN CITY OF SAMAL (IGACOS)',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'Ana Fe C. Luga',
                'email'           => 'samalpeso@gmail.com',
                'address'         => 'New City Hall Building Sitio Maag, Barangay Peaplata, Samal District, Island Garden City of Samal',
                'sort_order'      => 59,
            ],
            [
                'province'        => 'DAVAO DEL NORTE',
                'name'            => 'PESO ASUNCION',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'Eufronia J. Mangle, LPT',
                'email'           => 'pesoasuncion@gmail.com',
                'address'         => 'Purok 4, Cambanogoy, Asuncion, Davao del Norte',
                'sort_order'      => 60,
            ],
            [
                'province'        => 'DAVAO DEL NORTE',
                'name'            => 'PESO BRAULIO E. DUJALI',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'ALLAN S. PARAGUYA',
                'email'           => 'pesodujali@gmail.com',
                'address'         => 'Prk.6 Pob. Dujali, Braulio E. Dujali, Davao del Norte',
                'sort_order'      => 61,
            ],
            [
                'province'        => 'DAVAO DEL NORTE',
                'name'            => 'PESO CARMEN',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'JOHN KEVIN M. AMADOR',
                'email'           => 'justpesocarmen@yahoo.com',
                'address'         => 'Purok 7, Ising (Pob.), Carmen, Davao del Norte',
                'sort_order'      => 62,
            ],
            [
                'province'        => 'DAVAO DEL NORTE',
                'name'            => 'PESO KAPALONG',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'DELIA RAMOS PERNITES',
                'email'           => 'pesokapalongddn@gmail.com',
                'address'         => 'Maniki, Kapalong DDN',
                'sort_order'      => 63,
            ],
            [
                'province'        => 'DAVAO DEL NORTE',
                'name'            => 'PESO NEW CORELLA',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'Al B. Biotumas',
                'email'           => 'pesonewcorella@gmail.com',
                'address'         => 'Purok 2, Poblacion, New Corella',
                'sort_order'      => 64,
            ],
            [
                'province'        => 'DAVAO DEL NORTE',
                'name'            => 'PESO SAN ISIDRO',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'EMILY D. CABANLIT',
                'email'           => 'jash_eryne_triff@yahoo.com',
                'address'         => 'Prk. Cadena De Amor, Visayan Village, Tagum City',
                'sort_order'      => 65,
            ],
            [
                'province'        => 'DAVAO DEL NORTE',
                'name'            => 'PESO STO. TOMAS',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => null,
                'email'           => 'pesotomas23@gmail.com',
                'address'         => 'Feeder Road 3 Barangay Tibal og Santo Tomas Dav nor',
                'sort_order'      => 66,
            ],
            [
                'province'        => 'DAVAO DEL NORTE',
                'name'            => 'PESO TALAINGOD',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'EDWIN SUPERIORIDAD',
                'email'           => 'pesotalaingod72@gmail.com',
                'address'         => 'Balimba Hills,Talaingod, Davao del Norte',
                'sort_order'      => 67,
            ],
            [
                'province'        => 'DAVAO DEL NORTE',
                'name'            => "JPO ST. MARY'S COLLEGE OF TAGUM",
                'office_type_id'  => $JPO,
                'position_title'  => 'JPO MANAGER',
                'persons_name'    => 'Virginia L. Cordoves',
                'email'           => 'virginia_cordoves@yahoo.com',
                'address'         => "St. Mary's College of Tagum, Inc. Tagum City",
                'sort_order'      => 68,
            ],
            [
                'province'        => 'DAVAO DEL NORTE',
                'name'            => 'JPO UNIVERSITY OF MINDANAO TAGUM COLLEGE',
                'office_type_id'  => $JPO,
                'position_title'  => 'JPO MANAGER',
                'persons_name'    => 'ANSONA C. ARBOIZ',
                'email'           => 'eraaotagum@umindanao.edu.ph',
                'address'         => 'Mabini Street, Tagum City',
                'sort_order'      => 69,
            ],
            [
                'province'        => 'DAVAO DEL NORTE',
                'name'            => 'JPO UNIVERSITY OF MINDANAO PANABO COLLEGE',
                'office_type_id'  => $JPO,
                'position_title'  => 'JPO MANAGER',
                'persons_name'    => 'GLEZER V. NIEZ',
                'email'           => 'eraaopanabo@umindanao.edu.ph',
                'address'         => 'Sto. Nino, Panabo City, DDN',
                'sort_order'      => 70,
            ],
            [
                'province'        => 'DAVAO DEL NORTE',
                'name'            => 'JPO ACES POLYTECHNIC COLLEGE',
                'office_type_id'  => $JPO,
                'position_title'  => 'JPO MANAGER',
                'persons_name'    => 'MARIEFE S. POSPOS',
                'email'           => 'acespanabo.jpo@gmail.com',
                'address'         => 'Brgy San Francisco Panabo City',
                'sort_order'      => 71,
            ],
            [
                'province'        => 'DAVAO DEL NORTE',
                'name'            => 'JPO ACES TAGUM COLLEGE',
                'office_type_id'  => $JPO,
                'position_title'  => 'JPO MANAGER',
                'persons_name'    => 'ALFONSO R. VENTURES, MSIS',
                'email'           => 'atcdavnor@gmail.com',
                'address'         => 'Mankilam, Tagum City, Davao del Norte',
                'sort_order'      => 72,
            ],
            [
                'province'        => 'DAVAO DEL NORTE',
                'name'            => 'JPO DAVAO DEL NORTE STATE COLLEGE',
                'office_type_id'  => $JPO,
                'position_title'  => 'JPO MANAGER',
                'persons_name'    => 'MARICIELO PAULA E. FUNA',
                'email'           => 'jpo@dnsc.edu.ph',
                'address'         => 'BRGY. NEW VISAYAS, PANABO CITY',
                'sort_order'      => 73,
            ],
            [
                'province'        => 'DAVAO DEL NORTE',
                'name'            => 'JPO KAPALONG COLLEGE OF AGRICULTURE, SCIENCES AND TECHNOLOGY',
                'office_type_id'  => $JPO,
                'position_title'  => 'JPO MANAGER',
                'persons_name'    => 'RONEL G. DAGOHOY, DPA',
                'email'           => 'jpo@kcast.edu.ph',
                'address'         => 'Maniki, Kapalong, Davao del Norte',
                'sort_order'      => 74,
            ],
            [
                'province'        => 'DAVAO DEL NORTE',
                'name'            => 'JPO STO. TOMAS COLLEGE OF AGRICULTURE, SCINCE AND TECHNOLOGY',
                'office_type_id'  => $JPO,
                'position_title'  => 'JPO MANAGER',
                'persons_name'    => 'ANILYN C. AGUSPINA',
                'email'           => 'anilynstcastjpo@gmail.com',
                'address'         => 'STCAST, Santo Tomas, DDN',
                'sort_order'      => 75,
            ],
            [
                'province'        => 'DAVAO DEL NORTE',
                'name'            => 'JPO SAMAL ISLAND CITY COLLEGE',
                'office_type_id'  => $JPO,
                'position_title'  => 'JPO MANAGER',
                'persons_name'    => 'RICHARD S. JIMENEZ, RGC, RPm',
                'email'           => 'richard.filuga@yahoo.com',
                'address'         => "Datu Taganiog St., Brgy. Peaplata, Samal District, Island Garden City of Samal",
                'sort_order'      => 76,
            ],
            [
                'province'        => 'DAVAO DEL NORTE',
                'name'            => 'JPO NORTHLINK TECHNOLOGICAL COLLEGE INC.',
                'office_type_id'  => $JPO,
                'position_title'  => 'JPO MANAGER',
                'persons_name'    => 'GEANICA N. GARCIA, RPm',
                'email'           => 'geagarcia@northlink.edu.ph',
                'address'         => "Along Nat'l Highway, Brgy. New Pandan, Panabo City",
                'sort_order'      => 77,
            ],
            [
                'province'        => 'DAVAO DEL NORTE',
                'name'            => 'JPO UM PEAPLATA COLLEGE',
                'office_type_id'  => $JPO,
                'position_title'  => 'JPO MANAGER',
                'persons_name'    => 'HECTOR B. AGUILAR',
                'email'           => 'eraaopenaplata@umindanao.edu.ph',
                'address'         => 'OBENZA St. Peaplata, IGaCoS',
                'sort_order'      => 78,
            ],

            // ─── DAVAO CITY ───────────────────────────────────────────────────
            [
                'province'        => 'DAVAO CITY',
                'name'            => 'PESO DAVAO CITY',
                'office_type_id'  => $PESO,
                'position_title'  => 'PESO MANAGER',
                'persons_name'    => 'LILIBETH D. PANTINOPLE',
                'email'           => 'peso@davaocity.gov.ph davao_peso@yahoo.com',
                'address'         => 'DAVAO CITY RECREATIONAL CENTER (FORMERLY ALMENDRAS GYM), QUIMPO BOULEVARD, DAVAO CITY',
                'sort_order'      => 79,
            ],
            [
                'province'        => 'DAVAO CITY',
                'name'            => 'PESO AGDAO DISTRICT',
                'office_type_id'  => $PESO,
                'position_title'  => 'DISTRICT HEAD',
                'persons_name'    => 'ERWIN W. CAGAPE',
                'email'           => 'peso@davaocity.gov.ph davao_peso@yahoo.com',
                'address'         => 'AGDAO DISTRICT HALL, LAPU LAPU ST., DAVAO CITY',
                'sort_order'      => 80,
            ],
            [
                'province'        => 'DAVAO CITY',
                'name'            => 'PESO TALOMO DISTRICT',
                'office_type_id'  => $PESO,
                'position_title'  => 'DISTRICT HEAD',
                'persons_name'    => 'RENATO S. SALAZAR',
                'email'           => 'peso@davaocity.gov.ph davao_peso@yahoo.com',
                'address'         => '74-A, MATINA CROSSING, BRGY. HALL, DAVAO CITY',
                'sort_order'      => 81,
            ],
            [
                'province'        => 'DAVAO CITY',
                'name'            => 'PESO CALINAN DISTRICT',
                'office_type_id'  => $PESO,
                'position_title'  => 'DISTRICT HEAD',
                'persons_name'    => 'ROSELYN C. TAHIL',
                'email'           => 'peso@davaocity.gov.ph davao_peso@yahoo.com',
                'address'         => 'NEAR CALINAN, BRGY. HALL, CALINAN DISTRICT, DAVAO CITY',
                'sort_order'      => 82,
            ],
            [
                'province'        => 'DAVAO CITY',
                'name'            => 'PESO BUNAWAN DISTRICT',
                'office_type_id'  => $PESO,
                'position_title'  => 'DISTRICT HEAD',
                'persons_name'    => 'CAMILLE BIANCA E. SANCHEZ',
                'email'           => 'peso@davaocity.gov.ph davao_peso@yahoo.com',
                'address'         => 'KM. 23 BUNAWAN DISTRICT OFFICE',
                'sort_order'      => 83,
            ],
            [
                'province'        => 'DAVAO CITY',
                'name'            => 'PESO TUGBOK DISTRICT',
                'office_type_id'  => $PESO,
                'position_title'  => 'DISTRICT HEAD',
                'persons_name'    => 'CHARISSE E. TOLENTINO',
                'email'           => 'peso@davaocity.gov.ph davao_peso@yahoo.com',
                'address'         => 'MINTAL DISTRICT HALL, GUMAMELA ST., DAVAO CITY',
                'sort_order'      => 84,
            ],
            [
                'province'        => 'DAVAO CITY',
                'name'            => 'PESO BAGUIO DISTRICT',
                'office_type_id'  => $PESO,
                'position_title'  => 'DISTRICT HEAD',
                'persons_name'    => 'ALMA A. ARANCIS',
                'email'           => 'peso@davaocity.gov.ph davao_peso@yahoo.com',
                'address'         => 'PESO BAGUIO DISTRICT, BAGUIO PROPER, DAVAO CITY',
                'sort_order'      => 85,
            ],
            [
                'province'        => 'DAVAO CITY',
                'name'            => 'PESO BUHANGIN DISTRICT',
                'office_type_id'  => $PESO,
                'position_title'  => 'DISTRICT HEAD',
                'persons_name'    => 'SHIRLY D. SAHID',
                'email'           => 'peso@davaocity.gov.ph davao_peso@yahoo.com',
                'address'         => 'BUHANGIN GYM, BUHANGIN PROPER, DAVAO CITY',
                'sort_order'      => 86,
            ],
            [
                'province'        => 'DAVAO CITY',
                'name'            => 'PESO TORIL DISTRICT',
                'office_type_id'  => $PESO,
                'position_title'  => 'DISTRICT HEAD',
                'persons_name'    => 'MELINA I. ISIDRO',
                'email'           => 'peso@davaocity.gov.ph davao_peso@yahoo.com',
                'address'         => 'TORIL DISTRICT HALL, AGTON ST., TORIL PROPER, DAVAO CITY',
                'sort_order'      => 87,
            ],
            [
                'province'        => 'DAVAO CITY',
                'name'            => 'JPO UNIVERSITY OF MINDANAO (BOLTON CAMPUS)',
                'office_type_id'  => $JPO,
                'position_title'  => 'JPO MANAGER',
                'persons_name'    => 'REYNALDO C. CASTRO',
                'email'           => 'studentdev@umindanao.edu.ph',
                'address'         => 'BOLTON ST., POBLACION DISTRICT, DAVAO CITY',
                'sort_order'      => 88,
            ],
            [
                'province'        => 'DAVAO CITY',
                'name'            => 'JPO Holy Cross of Davao College',
                'office_type_id'  => $JPO,
                'position_title'  => 'JPO MANAGER',
                'persons_name'    => 'ROMIL L. TORREJOS',
                'email'           => 'externalrelations@hcdc.edu.ph torrejos@hcdc.edu.ph',
                'address'         => 'STA. ANA AVENUE COR. C. DE GUZMAN ST., BRGY. 14-B, DAVAO CITY',
                'sort_order'      => 89,
            ],
            [
                'province'        => 'DAVAO CITY',
                'name'            => 'JPO UNIVERSITY OF SOUTHEASTERN PHILIPPINES',
                'office_type_id'  => $JPO,
                'position_title'  => 'JPO MANAGER',
                'persons_name'    => 'DR. ALMA MAE G. SALINAS',
                'email'           => 'cac@usep.edu.ph',
                'address'         => 'IIGO ST., BO. OBRERO, DAVAO CITY',
                'sort_order'      => 90,
            ],
            [
                'province'        => 'DAVAO CITY',
                'name'            => 'JPO Mapa Malayan Colleges Mindanao',
                'office_type_id'  => $JPO,
                'position_title'  => 'JPO MANAGER',
                'persons_name'    => 'TRISHA MAE A. MENOY',
                'email'           => 'ccp@mcm.edu.ph',
                'address'         => 'Gen. Douglas MacArthur Hwy, Talomo, Davao City, 8000, Davao Del Sur',
                'sort_order'      => 91,
            ],
        ];

        foreach ($offices as $office) {
            $ptId = $titles[$office['position_title']] ?? null;
            FieldOffice::create([
                'province'          => $office['province'],
                'name'              => $office['name'],
                'office_type_id'    => $office['office_type_id'],
                'position_title_id' => $ptId,
                'persons_name'      => $office['persons_name'],
                'email'             => $office['email'],
                'address'           => $office['address'],
                'sort_order'        => $office['sort_order'],
            ]);
        }

        // ─── CAROUSEL SLIDES ──────────────────────────────────────────────────
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        PesoCarouselSlide::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $slides = [
            [
                'image_path' => 'images/peso-carousel/peso-carousel1.jpg',
                'sort_order' => 1,
                'is_active'  => 1,
            ],
            [
                'image_path' => 'images/peso-carousel/peso-carousel2.jpeg',
                'sort_order' => 2,
                'is_active'  => 1,
            ],
            [
                'image_path' => 'images/peso-carousel/peso-carousel3.png',
                'sort_order' => 3,
                'is_active'  => 1,
            ],
        ];

        foreach ($slides as $slide) {
            PesoCarouselSlide::create($slide);
        }
    }
}